### ISSUE TITLE
ase is missing from requirements?

### ISSUE THREAD

**Issue by ANogin** [ge-semtk/semtk-python3#10]
Revision 4e1f834e added the use of ase in to `semtk3/semtktable.py`, but it's not in `requirements.txt`, resulting in

```
ModuleNotFoundError: No module named 'ase'
Traceback (most recent call last):
[...]
    import semtk3
  File "/app/atl/.venv/lib/python3.8/site-packages/semtk3/__init__.py", line 24, in <module>
    from . import fdccacheclient
  File "/app/atl/.venv/lib/python3.8/site-packages/semtk3/fdccacheclient.py", line 17, in <module>
    from . import semtkasyncclient
  File "/app/atl/.venv/lib/python3.8/site-packages/semtk3/semtkasyncclient.py", line 17, in <module>
    from . import semtkclient
  File "/app/atl/.venv/lib/python3.8/site-packages/semtk3/semtkclient.py", line 21, in <module>
    from . import semtktable
  File "/app/atl/.venv/lib/python3.8/site-packages/semtk3/semtktable.py", line 27, in <module>
    from ase.db import row
ModuleNotFoundError: No module named 'ase'
```

**Comment by ANogin** [comment]
And similarly for 69a1d111, plotly and `semtk3/__init__.py`
